
# This file is automatically generated, you probably don't want to edit this

clinsigOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "clinsigOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            pre = NULL,
            post = NULL,
            groupingVar = NULL,
            dysNorms = "baselineValues",
            dys_mean = 0,
            dys_sd = 0,
            func_mean = 0,
            func_sd = 0,
            reliabilityMeasurement = -1,
            cutoffs = "a",
            higherBetter = TRUE,
            table = TRUE,
            showPercentage = FALSE,
            barplot = FALSE,
            showBarPlotAmount = FALSE,
            scatterplot = FALSE,
            showScatterPlotAmount = FALSE,
            manualColours = FALSE,
            recovered = "#2C9A3E",
            improved = "#3397CD",
            unchanged = "#CD7933",
            detoriated = "#C2371C",
            manualTicks = FALSE,
            tickIntervalX = 1,
            tickIntervalY = 1,
            showCutoffValue = FALSE,
            manualLimit = FALSE,
            xAxisLower = NULL,
            xAxisUpper = NULL,
            yAxisLower = NULL,
            yAxisUpper = NULL, ...) {

            super$initialize(
                package="ClinSig",
                name="clinsig",
                requiresData=TRUE,
                ...)

            private$..pre <- jmvcore::OptionVariable$new(
                "pre",
                pre,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..post <- jmvcore::OptionVariable$new(
                "post",
                post,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..groupingVar <- jmvcore::OptionVariable$new(
                "groupingVar",
                groupingVar,
                default=NULL)
            private$..dysNorms <- jmvcore::OptionList$new(
                "dysNorms",
                dysNorms,
                options=list(
                    "baselineValues",
                    "manualValues"),
                default="baselineValues")
            private$..dys_mean <- jmvcore::OptionNumber$new(
                "dys_mean",
                dys_mean,
                default=0)
            private$..dys_sd <- jmvcore::OptionNumber$new(
                "dys_sd",
                dys_sd,
                default=0)
            private$..func_mean <- jmvcore::OptionNumber$new(
                "func_mean",
                func_mean,
                default=0)
            private$..func_sd <- jmvcore::OptionNumber$new(
                "func_sd",
                func_sd,
                default=0)
            private$..reliabilityMeasurement <- jmvcore::OptionNumber$new(
                "reliabilityMeasurement",
                reliabilityMeasurement,
                default=-1,
                min=0,
                max=1)
            private$..cutoffs <- jmvcore::OptionList$new(
                "cutoffs",
                cutoffs,
                options=list(
                    "a",
                    "b",
                    "c"),
                default="a")
            private$..higherBetter <- jmvcore::OptionBool$new(
                "higherBetter",
                higherBetter,
                default=TRUE)
            private$..table <- jmvcore::OptionBool$new(
                "table",
                table,
                default=TRUE)
            private$..showPercentage <- jmvcore::OptionBool$new(
                "showPercentage",
                showPercentage,
                default=FALSE)
            private$..barplot <- jmvcore::OptionBool$new(
                "barplot",
                barplot,
                default=FALSE)
            private$..showBarPlotAmount <- jmvcore::OptionBool$new(
                "showBarPlotAmount",
                showBarPlotAmount,
                default=FALSE)
            private$..scatterplot <- jmvcore::OptionBool$new(
                "scatterplot",
                scatterplot,
                default=FALSE)
            private$..showScatterPlotAmount <- jmvcore::OptionBool$new(
                "showScatterPlotAmount",
                showScatterPlotAmount,
                default=FALSE)
            private$..manualColours <- jmvcore::OptionBool$new(
                "manualColours",
                manualColours,
                default=FALSE)
            private$..recovered <- jmvcore::OptionString$new(
                "recovered",
                recovered,
                default="#2C9A3E")
            private$..improved <- jmvcore::OptionString$new(
                "improved",
                improved,
                default="#3397CD")
            private$..unchanged <- jmvcore::OptionString$new(
                "unchanged",
                unchanged,
                default="#CD7933")
            private$..detoriated <- jmvcore::OptionString$new(
                "detoriated",
                detoriated,
                default="#C2371C")
            private$..manualTicks <- jmvcore::OptionBool$new(
                "manualTicks",
                manualTicks,
                default=FALSE)
            private$..tickIntervalX <- jmvcore::OptionNumber$new(
                "tickIntervalX",
                tickIntervalX,
                default=1)
            private$..tickIntervalY <- jmvcore::OptionNumber$new(
                "tickIntervalY",
                tickIntervalY,
                default=1)
            private$..showCutoffValue <- jmvcore::OptionBool$new(
                "showCutoffValue",
                showCutoffValue,
                default=FALSE)
            private$..manualLimit <- jmvcore::OptionBool$new(
                "manualLimit",
                manualLimit,
                default=FALSE)
            private$..xAxisLower <- jmvcore::OptionNumber$new(
                "xAxisLower",
                xAxisLower)
            private$..xAxisUpper <- jmvcore::OptionNumber$new(
                "xAxisUpper",
                xAxisUpper)
            private$..yAxisLower <- jmvcore::OptionNumber$new(
                "yAxisLower",
                yAxisLower)
            private$..yAxisUpper <- jmvcore::OptionNumber$new(
                "yAxisUpper",
                yAxisUpper)

            self$.addOption(private$..pre)
            self$.addOption(private$..post)
            self$.addOption(private$..groupingVar)
            self$.addOption(private$..dysNorms)
            self$.addOption(private$..dys_mean)
            self$.addOption(private$..dys_sd)
            self$.addOption(private$..func_mean)
            self$.addOption(private$..func_sd)
            self$.addOption(private$..reliabilityMeasurement)
            self$.addOption(private$..cutoffs)
            self$.addOption(private$..higherBetter)
            self$.addOption(private$..table)
            self$.addOption(private$..showPercentage)
            self$.addOption(private$..barplot)
            self$.addOption(private$..showBarPlotAmount)
            self$.addOption(private$..scatterplot)
            self$.addOption(private$..showScatterPlotAmount)
            self$.addOption(private$..manualColours)
            self$.addOption(private$..recovered)
            self$.addOption(private$..improved)
            self$.addOption(private$..unchanged)
            self$.addOption(private$..detoriated)
            self$.addOption(private$..manualTicks)
            self$.addOption(private$..tickIntervalX)
            self$.addOption(private$..tickIntervalY)
            self$.addOption(private$..showCutoffValue)
            self$.addOption(private$..manualLimit)
            self$.addOption(private$..xAxisLower)
            self$.addOption(private$..xAxisUpper)
            self$.addOption(private$..yAxisLower)
            self$.addOption(private$..yAxisUpper)
        }),
    active = list(
        pre = function() private$..pre$value,
        post = function() private$..post$value,
        groupingVar = function() private$..groupingVar$value,
        dysNorms = function() private$..dysNorms$value,
        dys_mean = function() private$..dys_mean$value,
        dys_sd = function() private$..dys_sd$value,
        func_mean = function() private$..func_mean$value,
        func_sd = function() private$..func_sd$value,
        reliabilityMeasurement = function() private$..reliabilityMeasurement$value,
        cutoffs = function() private$..cutoffs$value,
        higherBetter = function() private$..higherBetter$value,
        table = function() private$..table$value,
        showPercentage = function() private$..showPercentage$value,
        barplot = function() private$..barplot$value,
        showBarPlotAmount = function() private$..showBarPlotAmount$value,
        scatterplot = function() private$..scatterplot$value,
        showScatterPlotAmount = function() private$..showScatterPlotAmount$value,
        manualColours = function() private$..manualColours$value,
        recovered = function() private$..recovered$value,
        improved = function() private$..improved$value,
        unchanged = function() private$..unchanged$value,
        detoriated = function() private$..detoriated$value,
        manualTicks = function() private$..manualTicks$value,
        tickIntervalX = function() private$..tickIntervalX$value,
        tickIntervalY = function() private$..tickIntervalY$value,
        showCutoffValue = function() private$..showCutoffValue$value,
        manualLimit = function() private$..manualLimit$value,
        xAxisLower = function() private$..xAxisLower$value,
        xAxisUpper = function() private$..xAxisUpper$value,
        yAxisLower = function() private$..yAxisLower$value,
        yAxisUpper = function() private$..yAxisUpper$value),
    private = list(
        ..pre = NA,
        ..post = NA,
        ..groupingVar = NA,
        ..dysNorms = NA,
        ..dys_mean = NA,
        ..dys_sd = NA,
        ..func_mean = NA,
        ..func_sd = NA,
        ..reliabilityMeasurement = NA,
        ..cutoffs = NA,
        ..higherBetter = NA,
        ..table = NA,
        ..showPercentage = NA,
        ..barplot = NA,
        ..showBarPlotAmount = NA,
        ..scatterplot = NA,
        ..showScatterPlotAmount = NA,
        ..manualColours = NA,
        ..recovered = NA,
        ..improved = NA,
        ..unchanged = NA,
        ..detoriated = NA,
        ..manualTicks = NA,
        ..tickIntervalX = NA,
        ..tickIntervalY = NA,
        ..showCutoffValue = NA,
        ..manualLimit = NA,
        ..xAxisLower = NA,
        ..xAxisUpper = NA,
        ..yAxisLower = NA,
        ..yAxisUpper = NA)
)

clinsigResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "clinsigResults",
    inherit = jmvcore::Group,
    active = list(
        table = function() private$.items[["table"]],
        barplot = function() private$.items[["barplot"]],
        scatterplot = function() private$.items[["scatterplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Clinical Significance")
            self$add(jmvcore::Table$new(
                options=options,
                name="table",
                title="Patient status after treatment",
                rows=0,
                columns=list(
                    list(
                        `name`="Grouping", 
                        `superTitle`="Grouping", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Detoriated", 
                        `superTitle`="Detoriated", 
                        `title`="Detoriated", 
                        `type`="number"),
                    list(
                        `name`="DetoriatedPercent", 
                        `superTitle`="Detoriated", 
                        `title`="%", 
                        `visible`=FALSE, 
                        `type`="number"),
                    list(
                        `name`="Improved", 
                        `superTitle`="Improved", 
                        `title`="Improved", 
                        `type`="number"),
                    list(
                        `name`="ImprovedPercent", 
                        `superTitle`="Improved", 
                        `title`="%", 
                        `visible`=FALSE, 
                        `type`="number"),
                    list(
                        `name`="Recovered", 
                        `superTitle`="Recovered", 
                        `title`="Recovered", 
                        `type`="number"),
                    list(
                        `name`="RecoveredPercent", 
                        `superTitle`="Recovered", 
                        `title`="%", 
                        `visible`=FALSE, 
                        `type`="number"),
                    list(
                        `name`="Unchanged", 
                        `superTitle`="Unchanged", 
                        `title`="Unchanged", 
                        `type`="number"),
                    list(
                        `name`="UnchangedPercent", 
                        `superTitle`="Unchanged", 
                        `title`="%", 
                        `visible`=FALSE, 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="barplot",
                title="Bar plot",
                width=600,
                height=400,
                renderFun=".barplot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="scatterplot",
                title="Scatter plot",
                width=600,
                height=400,
                renderFun=".scatterplot"))}))

clinsigBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "clinsigBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ClinSig",
                name = "clinsig",
                version = c(1,0,0),
                options = options,
                results = clinsigResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Clinical Significance
#'
#' 
#' @param data .
#' @param pre .
#' @param post .
#' @param groupingVar .
#' @param dysNorms .
#' @param dys_mean .
#' @param dys_sd .
#' @param func_mean .
#' @param func_sd .
#' @param reliabilityMeasurement .
#' @param cutoffs .
#' @param higherBetter .
#' @param table .
#' @param showPercentage .
#' @param barplot .
#' @param showBarPlotAmount .
#' @param scatterplot .
#' @param showScatterPlotAmount .
#' @param manualColours .
#' @param recovered .
#' @param improved .
#' @param unchanged .
#' @param detoriated .
#' @param manualTicks .
#' @param tickIntervalX .
#' @param tickIntervalY .
#' @param showCutoffValue .
#' @param manualLimit .
#' @param xAxisLower .
#' @param xAxisUpper .
#' @param yAxisLower .
#' @param yAxisUpper .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$barplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$scatterplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$table$asDF}
#'
#' \code{as.data.frame(results$table)}
#'
#' @export
clinsig <- function(
    data,
    pre,
    post,
    groupingVar = NULL,
    dysNorms = "baselineValues",
    dys_mean = 0,
    dys_sd = 0,
    func_mean = 0,
    func_sd = 0,
    reliabilityMeasurement = -1,
    cutoffs = "a",
    higherBetter = TRUE,
    table = TRUE,
    showPercentage = FALSE,
    barplot = FALSE,
    showBarPlotAmount = FALSE,
    scatterplot = FALSE,
    showScatterPlotAmount = FALSE,
    manualColours = FALSE,
    recovered = "#2C9A3E",
    improved = "#3397CD",
    unchanged = "#CD7933",
    detoriated = "#C2371C",
    manualTicks = FALSE,
    tickIntervalX = 1,
    tickIntervalY = 1,
    showCutoffValue = FALSE,
    manualLimit = FALSE,
    xAxisLower,
    xAxisUpper,
    yAxisLower,
    yAxisUpper) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("clinsig requires jmvcore to be installed (restart may be required)")

    if ( ! missing(pre)) pre <- jmvcore::resolveQuo(jmvcore::enquo(pre))
    if ( ! missing(post)) post <- jmvcore::resolveQuo(jmvcore::enquo(post))
    if ( ! missing(groupingVar)) groupingVar <- jmvcore::resolveQuo(jmvcore::enquo(groupingVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(pre), pre, NULL),
            `if`( ! missing(post), post, NULL),
            `if`( ! missing(groupingVar), groupingVar, NULL))


    options <- clinsigOptions$new(
        pre = pre,
        post = post,
        groupingVar = groupingVar,
        dysNorms = dysNorms,
        dys_mean = dys_mean,
        dys_sd = dys_sd,
        func_mean = func_mean,
        func_sd = func_sd,
        reliabilityMeasurement = reliabilityMeasurement,
        cutoffs = cutoffs,
        higherBetter = higherBetter,
        table = table,
        showPercentage = showPercentage,
        barplot = barplot,
        showBarPlotAmount = showBarPlotAmount,
        scatterplot = scatterplot,
        showScatterPlotAmount = showScatterPlotAmount,
        manualColours = manualColours,
        recovered = recovered,
        improved = improved,
        unchanged = unchanged,
        detoriated = detoriated,
        manualTicks = manualTicks,
        tickIntervalX = tickIntervalX,
        tickIntervalY = tickIntervalY,
        showCutoffValue = showCutoffValue,
        manualLimit = manualLimit,
        xAxisLower = xAxisLower,
        xAxisUpper = xAxisUpper,
        yAxisLower = yAxisLower,
        yAxisUpper = yAxisUpper)

    analysis <- clinsigClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

