
# This file is automatically generated, you probably don't want to edit this

clinsigOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "clinsigOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            pre = NULL,
            post = NULL,
            groupingVar = NULL,
            groupingBool = FALSE,
            dysNorms = "baselineValues",
            dys_mean = 0,
            dys_std = 0,
            func_mean = 0,
            func_std = 0,
            valueOfR = NULL,
            cutoffs = "a", ...) {

            super$initialize(
                package="ClinSig",
                name="clinsig",
                requiresData=TRUE,
                ...)

            private$..pre <- jmvcore::OptionVariable$new(
                "pre",
                pre,
                suggested=list(
                    "continuous"))
            private$..post <- jmvcore::OptionVariable$new(
                "post",
                post,
                suggested=list(
                    "continuous"))
            private$..groupingVar <- jmvcore::OptionVariable$new(
                "groupingVar",
                groupingVar,
                default=NULL,
                suggested=list(
                    "continuous",
                    "nominal",
                    "ordinal"))
            private$..groupingBool <- jmvcore::OptionBool$new(
                "groupingBool",
                groupingBool,
                default=FALSE)
            private$..dysNorms <- jmvcore::OptionList$new(
                "dysNorms",
                dysNorms,
                options=list(
                    "baselineValues",
                    "manualValues"),
                default="baselineValues")
            private$..dys_mean <- jmvcore::OptionNumber$new(
                "dys_mean",
                dys_mean,
                default=0)
            private$..dys_std <- jmvcore::OptionNumber$new(
                "dys_std",
                dys_std,
                default=0)
            private$..func_mean <- jmvcore::OptionNumber$new(
                "func_mean",
                func_mean,
                default=0)
            private$..func_std <- jmvcore::OptionNumber$new(
                "func_std",
                func_std,
                default=0)
            private$..valueOfR <- jmvcore::OptionNumber$new(
                "valueOfR",
                valueOfR,
                min=0,
                max=1)
            private$..cutoffs <- jmvcore::OptionList$new(
                "cutoffs",
                cutoffs,
                options=list(
                    "a",
                    "b",
                    "c"),
                default="a")

            self$.addOption(private$..pre)
            self$.addOption(private$..post)
            self$.addOption(private$..groupingVar)
            self$.addOption(private$..groupingBool)
            self$.addOption(private$..dysNorms)
            self$.addOption(private$..dys_mean)
            self$.addOption(private$..dys_std)
            self$.addOption(private$..func_mean)
            self$.addOption(private$..func_std)
            self$.addOption(private$..valueOfR)
            self$.addOption(private$..cutoffs)
        }),
    active = list(
        pre = function() private$..pre$value,
        post = function() private$..post$value,
        groupingVar = function() private$..groupingVar$value,
        groupingBool = function() private$..groupingBool$value,
        dysNorms = function() private$..dysNorms$value,
        dys_mean = function() private$..dys_mean$value,
        dys_std = function() private$..dys_std$value,
        func_mean = function() private$..func_mean$value,
        func_std = function() private$..func_std$value,
        valueOfR = function() private$..valueOfR$value,
        cutoffs = function() private$..cutoffs$value),
    private = list(
        ..pre = NA,
        ..post = NA,
        ..groupingVar = NA,
        ..groupingBool = NA,
        ..dysNorms = NA,
        ..dys_mean = NA,
        ..dys_std = NA,
        ..func_mean = NA,
        ..func_std = NA,
        ..valueOfR = NA,
        ..cutoffs = NA)
)

clinsigResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "clinsigResults",
    inherit = jmvcore::Group,
    active = list(
        table = function() private$.items[["table"]],
        plot = function() private$.items[["plot"]],
        dotplot = function() private$.items[["dotplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Clinical Significance")
            self$add(jmvcore::Table$new(
                options=options,
                name="table",
                title="Clinical Significance",
                rows=1,
                columns=list(
                    list(
                        `name`="patient_status", 
                        `title`="Patient Status:", 
                        `type`="text"),
                    list(
                        `name`="Detoriated", 
                        `type`="number"),
                    list(
                        `name`="Improved", 
                        `type`="number"),
                    list(
                        `name`="Recovered", 
                        `type`="number"),
                    list(
                        `name`="Unchanged", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Descriptives Plot",
                width=400,
                height=300,
                renderFun=".plot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="dotplot",
                title="Scatter Plot",
                width=600,
                height=400,
                renderFun=".dotplot"))}))

clinsigBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "clinsigBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ClinSig",
                name = "clinsig",
                version = c(1,0,0),
                options = options,
                results = clinsigResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Clinical Significance
#'
#' 
#' @param data .
#' @param pre .
#' @param post .
#' @param groupingVar .
#' @param groupingBool .
#' @param dysNorms .
#' @param dys_mean .
#' @param dys_std .
#' @param func_mean .
#' @param func_std .
#' @param valueOfR .
#' @param cutoffs .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$dotplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$table$asDF}
#'
#' \code{as.data.frame(results$table)}
#'
#' @export
clinsig <- function(
    data,
    pre,
    post,
    groupingVar = NULL,
    groupingBool = FALSE,
    dysNorms = "baselineValues",
    dys_mean = 0,
    dys_std = 0,
    func_mean = 0,
    func_std = 0,
    valueOfR,
    cutoffs = "a") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("clinsig requires jmvcore to be installed (restart may be required)")

    if ( ! missing(pre)) pre <- jmvcore::resolveQuo(jmvcore::enquo(pre))
    if ( ! missing(post)) post <- jmvcore::resolveQuo(jmvcore::enquo(post))
    if ( ! missing(groupingVar)) groupingVar <- jmvcore::resolveQuo(jmvcore::enquo(groupingVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(pre), pre, NULL),
            `if`( ! missing(post), post, NULL),
            `if`( ! missing(groupingVar), groupingVar, NULL))


    options <- clinsigOptions$new(
        pre = pre,
        post = post,
        groupingVar = groupingVar,
        groupingBool = groupingBool,
        dysNorms = dysNorms,
        dys_mean = dys_mean,
        dys_std = dys_std,
        func_mean = func_mean,
        func_std = func_std,
        valueOfR = valueOfR,
        cutoffs = cutoffs)

    analysis <- clinsigClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

